version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/joberchip-be-demo
    overwrite: yes

permissions:
  - object: /
    patter: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu